### ISSUE TITLE
MVP: Visualize tones

### ISSUE THREAD

**Issue by iver56** [glaar/js-midi-player#1]
## ToDo:
 - [x] Create a datatable from MIDI file with: Note, Start, Stop, Length( stop - start ), etc.
- [x] Create a notegrid-drawer that uses the datatable as input, and return a visualization of the datatable.
- [x] Create scrolleffect on the notegrid, so that the midi song is synced with the a stationary
 player head or player line.

**Comment by glaar** [comment]
## ToDo:
 - [ ] Create a datatable from MIDI file with: Note, Start, Stop, Length( stop - start ), etc.
- [ ] Create a notegrid-drawer that uses the datatable as input, and return a visualization of the datatable.
- [ ] Create scrolleffect on the notegrid, so that the midi song is synced with the a stationary
 player head or player line.

**Comment by iver56** [comment]
Yep, sounds good 👍
